export const CASHBACK_FORM_PERCENTAGE_PLACEHOLDER = 'Процент';

export const CASHBACK_FORM_PERCENTAGE_MIN_VALUE = 1;
export const CASHBACK_FORM_PERCENTAGE_MAX_VALUE = 100;

export const CASHBACK_FORM_PERCENTAGE_CHIPS = [
    CASHBACK_FORM_PERCENTAGE_MIN_VALUE,
    2,
    3,
    5,
    10,
    15,
    25,
    CASHBACK_FORM_PERCENTAGE_MAX_VALUE,
];
